# Generated by Django 6.0 on 2025-12-14 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
