# Generated by Django 5.2.9 on 2025-12-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsmodel',
            options={'permissions': [('assign_project', 'Can assign a project to users')]},
        ),
    ]
