# Generated by Django 5.2.9 on 2025-12-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmembers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsmodel',
            options={'permissions': [('assign_project', 'Can assign a project to users'), ('add_members', 'Can add a user to a project')]},
        ),
    ]
