# Generated by Django 5.2.9 on 2026-01-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
