# Generated by Django 5.2.9 on 2026-02-23 18:25

import datetime
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectsmodel_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsmodel",
            name="priority",
            field=django_enum.fields.EnumCharField(
                choices=[("LOW", "low"), ("MEDIUM", "medium"), ("HIGH", "high")],
                default="LOW",
                max_length=6,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectsmodel",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("ACTIVE", "active"),
                    ("COMPLETED", "completed"),
                    ("ON_HOLD", "on_hold"),
                ],
                default="ACTIVE",
                max_length=9,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="projectsmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "COMPLETED", "ON_HOLD"])),
                name="projects_ProjectsModel_status_ProjectStatusEnum",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsmodel",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", ["LOW", "MEDIUM", "HIGH"])),
                name="projects_ProjectsModel_priority_PriorityEnum",
            ),
        ),
    ]
