# Generated by Django 5.2.9 on 2026-03-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectsmodel_priority_projectsmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
