# Generated by Django 5.2.9 on 2026-05-05 07:52

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectsmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='priority',
            field=django_enum.fields.EnumCharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='MEDIUM', max_length=6),
        ),
        migrations.AlterField(
            model_name='projectsmodel',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('ACTIVE', 'active'), ('COMPLETED', 'completed'), ('ON_HOLD', 'on_hold')], default='ACTIVE', max_length=9),
        ),
    ]
