# Generated by Django 5.2.9 on 2026-05-01 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_seedrun_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeededObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeded_objects', to='core.seedrun')),
            ],
            options={
                'indexes': [models.Index(fields=['seed_run', 'model_label'], name='core_seeded_seed_ru_48de38_idx')],
                'unique_together': {('seed_run', 'model_label', 'object_id')},
            },
        ),
    ]
