# Generated by Django 5.2.9 on 2026-01-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
