# Generated by Django 5.2.9 on 2026-01-30 05:10

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', django_enum.fields.EnumCharField(blank=True, choices=[('meeting', 'Meeting'), ('task', 'Task'), ('deadline', 'Deadline'), ('reminder', 'Reminder')], max_length=8, null=True)),
                ('priority', django_enum.fields.EnumCharField(blank=True, choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=6, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('event_type__in', ['meeting', 'task', 'deadline', 'reminder']), ('event_type__isnull', True), _connector='OR'), name='Calendar_CalendarEvent_event_type_EventTypesEnum'), models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'MEDIUM', 'HIGH']), ('priority__isnull', True), _connector='OR'), name='Calendar_CalendarEvent_priority_PriorityEnum')],
            },
        ),
    ]
