# Generated by Django 5.2.9 on 2026-03-11 05:55

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
        ('projects', '0008_alter_projectsmodel_description'),
        ('tasks', '0010_alter_taskmodel_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month'), ('AGENDA', 'Agenda')], default='WEEK', max_length=20)),
                ('show_weekends', models.BooleanField(default=True)),
                ('show_tasks', models.BooleanField(default=True)),
                ('show_milestones', models.BooleanField(default=True)),
                ('show_meetings', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('priority', django_enum.fields.EnumCharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='MEDIUM', max_length=6)),
                ('status', django_enum.fields.EnumCharField(choices=[('TO_DO', 'to_do'), ('IN_PROGRESS', 'in_progress'), ('IN_REVIEW', 'in_review'), ('DONE', 'done')], default='TO_DO', max_length=11)),
                ('create_calendar_event', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskDeadlineSync',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deadline_sync', serialize=False, to='tasks.taskmodel')),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['event_date', 'start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='Calendar_CalendarEvent_event_type_EventTypesEnum',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='linked_project',
            field=models.ForeignKey(blank=True, help_text='Link this event to a specific project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='linked_task',
            field=models.ForeignKey(blank=True, help_text='Link this event to a specific task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='tasks.taskmodel'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_pattern',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLYWeekly', 'Weekly'), ('MONTHLYMonthly', 'Monthly')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_minutes_before',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='send_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=django_enum.fields.EnumCharField(choices=[('MEETING', 'Meeting'), ('TASK', 'Task'), ('DEADLINE', 'Deadline'), ('REMINDER', 'Reminder')], default='TASK', max_length=8),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_date', 'user'], name='Calendar_ca_event_d_f6a5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['linked_task'], name='Calendar_ca_linked__963406_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['linked_project'], name='Calendar_ca_linked__ce94a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['MEETING', 'TASK', 'DEADLINE', 'REMINDER'])), name='Calendar_CalendarEvent_event_type_EventTypesEnum'),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_pattern__in', ['DAILY', 'WEEKLYWeekly', 'MONTHLYMonthly']), ('recurrence_pattern__isnull', True), _connector='OR'), name='Calendar_CalendarEvent_recurrence_pattern_RecurrenceEnums'),
        ),
        migrations.AddField(
            model_name='calendarview',
            name='filtered_projects',
            field=models.ManyToManyField(blank=True, related_name='calendar_filters', to='projects.projectsmodel'),
        ),
        migrations.AddField(
            model_name='calendarview',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.projectsmodel'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['project', 'due_date'], name='Calendar_pr_project_eacca5_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'MEDIUM', 'HIGH'])), name='Calendar_ProjectMilestone_priority_PriorityEnum'),
        ),
        migrations.AddConstraint(
            model_name='projectmilestone',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['TO_DO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE'])), name='Calendar_ProjectMilestone_status_StatusEnum'),
        ),
    ]
