# Generated by Django 5.2.9 on 2026-05-01 04:24

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_calendarview_projectmilestone_taskdeadlinesync_and_more'),
        ('projects', '0008_alter_projectsmodel_description'),
        ('tasks', '0010_alter_taskmodel_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendarevent',
            name='Calendar_CalendarEvent_recurrence_pattern_RecurrenceEnums',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_pattern',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=7, null=True),
        ),
        migrations.AddConstraint(
            model_name='calendarevent',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence_pattern__in', ['DAILY', 'WEEKLY', 'MONTHLY']), ('recurrence_pattern__isnull', True), _connector='OR'), name='Calendar_CalendarEvent_recurrence_pattern_RecurrenceEnums'),
        ),
    ]
