# Generated by Django 5.2.9 on 2026-04-07 18:21

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_alter_projectsmodel_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', django_enum.fields.EnumCharField(choices=[('project', 'Project'), ('task', 'Task'), ('user', 'User'), ('comment', 'Comment'), ('system', 'System')], max_length=7)),
                ('action', django_enum.fields.EnumCharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('registered', 'Registered')], max_length=10)),
                ('target_type', models.CharField(blank=True, default='', max_length=60)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='projects.projectsmodel')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['module', 'action', 'occurred_at'], name='audit_globa_module_e56761_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_globa_target__96a5c5_idx'), models.Index(fields=['actor', 'occurred_at'], name='audit_globa_actor_i_ea56ea_idx'), models.Index(fields=['project', 'occurred_at'], name='audit_globa_project_6dac5b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('module__in', ['project', 'task', 'user', 'comment', 'system'])), name='audit_GlobalAuditLog_module_AuditModule'), models.CheckConstraint(condition=models.Q(('action__in', ['created', 'updated', 'deleted', 'registered'])), name='audit_GlobalAuditLog_action_AuditAction')],
            },
        ),
    ]
