# Generated by Django 5.2.9 on 2025-12-19 06:07

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_projectmembers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', django_enum.fields.EnumCharField(blank=True, choices=[('OPEN', 'open'), ('IN_PROGRESS', 'in_progress'), ('DONE', 'done')], max_length=11, null=True)),
                ('priority', django_enum.fields.EnumCharField(blank=True, choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], max_length=6, null=True)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='projects.projectsmodel')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'IN_PROGRESS', 'DONE']), ('status__isnull', True), _connector='OR'), name='tasks_TaskModel_status_StatusEnum'), models.CheckConstraint(condition=models.Q(('priority__in', ['LOW', 'MEDIUM', 'HIGH']), ('priority__isnull', True), _connector='OR'), name='tasks_TaskModel_priority_PriorityEnum')],
            },
        ),
    ]
