# Generated by Django 5.2.9 on 2025-12-23 12:55

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskmodel_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', django_enum.fields.EnumCharField(choices=[('status', 'Status'), ('priority', 'Priority'), ('assigned_to', 'Assigned To'), ('due_date', 'Due Date'), ('title', 'Title'), ('description', 'Description')], max_length=11)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='tasks.taskmodel')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('field_changed__in', ['status', 'priority', 'assigned_to', 'due_date', 'title', 'description'])), name='tasks_TaskHistoryModel_field_changed_TaskFieldEnum')],
            },
        ),
    ]
