# Generated by Django 5.2.9 on 2026-01-21 04:52

import django.db.models.deletion
import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_taskmodel_updated_at_alter_commentmodel_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_enum.fields.EnumCharField(blank=True, choices=[('OPEN', 'open'), ('IN_PROGRESS', 'in_progress'), ('DONE', 'done')], max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='taskmodel',
            name='tasks_TaskModel_status_StatusEnum',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='assigned_to',
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['OPEN', 'IN_PROGRESS', 'DONE']), ('name__isnull', True), _connector='OR'), name='tasks_Status_name_StatusEnum'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status', to='tasks.status'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.taskmodel'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
