# Generated by Django 5.2.9 on 2026-01-28 03:49

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectsmodel_updated_at'),
        ('tasks', '0007_taskmodel_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('OPEN', 'open'), ('IN_PROGRESS', 'in_progress'), ('DONE', 'done')], max_length=11, null=True),
        ),
        migrations.AddConstraint(
            model_name='taskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'IN_PROGRESS', 'DONE']), ('status__isnull', True), _connector='OR'), name='tasks_TaskModel_status_StatusEnum'),
        ),
    ]
