# Generated by Django 5.2.9 on 2026-01-28 06:14

import django_enum.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectsmodel_updated_at'),
        ('tasks', '0008_alter_taskmodel_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='status',
            name='tasks_Status_name_StatusEnum',
        ),
        migrations.RemoveConstraint(
            model_name='taskmodel',
            name='tasks_TaskModel_status_StatusEnum',
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('TO_DO', 'to_do'), ('IN_PROGRESS', 'in_progress'), ('IN_REVIEW', 'in_review'), ('DONE', 'done')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=django_enum.fields.EnumCharField(blank=True, choices=[('TO_DO', 'to_do'), ('IN_PROGRESS', 'in_progress'), ('IN_REVIEW', 'in_review'), ('DONE', 'done')], max_length=11, null=True),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.CheckConstraint(condition=models.Q(('name__in', ['TO_DO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE']), ('name__isnull', True), _connector='OR'), name='tasks_Status_name_StatusEnum'),
        ),
        migrations.AddConstraint(
            model_name='taskmodel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['TO_DO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE']), ('status__isnull', True), _connector='OR'), name='tasks_TaskModel_status_StatusEnum'),
        ),
    ]
