# Generated by Django 5.2.9 on 2026-03-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_status_tasks_status_name_statusenum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
